// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX6hxAdTNCPiSdKPm1jA6GqUF1pgIYQhs',
    appId: '1:1052667467572:web:4370610c414dc50fb6f761',
    messagingSenderId: '1052667467572',
    projectId: 'oneday-af343',
    authDomain: 'oneday-af343.firebaseapp.com',
    storageBucket: 'oneday-af343.firebasestorage.app',
    measurementId: 'G-NT6QDQL4N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkmTdDqaUq-ExciBTcFkswiMQc3U0Gkks',
    appId: '1:437385978364:android:e4d79c960b84ffce7d1279',
    messagingSenderId: '437385978364',
    projectId: 'oneday-b3715',
    storageBucket: 'oneday-b3715.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVXuAmXy_v2qM-CI_B4Oqy5WruAj-L_F8',
    appId: '1:437385978364:ios:8139c77ca0c7c4557d1279',
    messagingSenderId: '437385978364',
    projectId: 'oneday-b3715',
    storageBucket: 'oneday-b3715.firebasestorage.app',
    iosBundleId: 'com.urdev.oneday.oneday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjmxzpdT0ibjNOIU5P0lZjjDH8MgW9XCs',
    appId: '1:1052667467572:ios:0ccb01c2c40fe098b6f761',
    messagingSenderId: '1052667467572',
    projectId: 'oneday-af343',
    storageBucket: 'oneday-af343.firebasestorage.app',
    androidClientId: '1052667467572-8smf5kpcpbniordljeb0ed3d2bt58hei.apps.googleusercontent.com',
    iosClientId: '1052667467572-iu5la8nc7n9qqqkvje3ip0bljmejrpbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.simaba',
  );
}